printWidth: 80
proseWrap: always
useTabs: false
tabWidth: 2
overrides:
  - files: ["*.props", "*.csproj"]
    options:
      parser: html
      htmlWhitespaceSensitivity: ignore
      printWidth: 100
